import { ZoneConfig } from './ZoneConfig';
import { EnemyType } from '../../entities/enemies/EnemyTypes';
import { HazardType } from '../../entities/hazards/HazardTypes';
import { PickupType } from '../../entities/pickups/PickupTypes';

export const ZONE_CONFIGS: ZoneConfig[] = [
  {
    // Zone 1: tutorial zone — asteroids only, no enemies
    id: 1,
    name: 'Starfield Ingress',
    scoreToClear: 250,
    waveCount: 8,
    spawnIntervalMs: { start: 1950, min: 650 },
    maxAsteroids: 20,
    asteroidSizeRange: [20, 50],
    asteroidSpeedRange: [400, 620],
    asteroidDamageRange: [20, 60],
    playfield: { horizontalLimit: 1400, verticalLimit: 700 },
    driftPattern: 'none',
    background: { starColor: 0xffffff, minSpeed: 50, maxSpeed: 200 },
    audioTrackId: 'level1',
    enemyPalette: [],
    hazardPalette: [],
    pickupPalette: [PickupType.SHIELD_CELL],
    pickupDropRate: 0,
  },
  {
    // Zone 2: Shatter Belt — pirate raiders, light hazards
    id: 2,
    name: 'Shatter Belt',
    scoreToClear: 375,
    waveCount: 8,
    spawnIntervalMs: { start: 1600, min: 850 },
    maxAsteroids: 25,
    asteroidSizeRange: [14, 36],
    asteroidSpeedRange: [420, 720],
    asteroidDamageRange: [18, 45],
    playfield: { horizontalLimit: 1400, verticalLimit: 700 },
    driftPattern: 'none',
    background: { starColor: 0x88ffff, minSpeed: 70, maxSpeed: 240 },
    audioTrackId: 'level2',
    enemyPalette: [EnemyType.RAIDER, EnemyType.STRIKER, EnemyType.CARRIER_POD],
    hazardPalette: [HazardType.DEBRIS_FIELD],
    pickupPalette: [PickupType.SHIELD_CELL, PickupType.HULL_PATCH, PickupType.SCORE_CACHE],
    bossId: 'razorback',
    pickupDropRate: 0.15,
  },
  {
    // Zone 3: Graveyard Drift — slow, heavy enemies and proximity mines
    id: 3,
    name: 'Graveyard Drift',
    scoreToClear: 560,
    waveCount: 8,
    spawnIntervalMs: { start: 1900, min: 1100 },
    maxAsteroids: 22,
    asteroidSizeRange: [30, 70],
    asteroidSpeedRange: [260, 460],
    asteroidDamageRange: [40, 90],
    playfield: { horizontalLimit: 1400, verticalLimit: 700 },
    driftPattern: 'none',
    background: { starColor: 0xffddaa, minSpeed: 40, maxSpeed: 160 },
    audioTrackId: 'level3',
    enemyPalette: [EnemyType.BOMBER, EnemyType.TURRET_DRONE, EnemyType.SENTINEL],
    hazardPalette: [HazardType.DEBRIS_FIELD, HazardType.PROXIMITY_MINE],
    pickupPalette: [PickupType.HULL_PATCH, PickupType.SHIELD_CELL, PickupType.AMMO_CACHE],
    bossId: 'mortuary',
    pickupDropRate: 0.18,
  },
  {
    // Zone 4: Needle Field — narrow corridor, fast enemies
    id: 4,
    name: 'Needle Field',
    scoreToClear: 840,
    waveCount: 8,
    spawnIntervalMs: { start: 1400, min: 700 },
    maxAsteroids: 28,
    asteroidSizeRange: [12, 28],
    asteroidSpeedRange: [520, 820],
    asteroidDamageRange: [20, 55],
    playfield: { horizontalLimit: 950, verticalLimit: 520 },
    driftPattern: 'spiral',
    background: { starColor: 0xaaddff, minSpeed: 80, maxSpeed: 280 },
    audioTrackId: 'level4',
    enemyPalette: [EnemyType.STRIKER, EnemyType.RAIDER, EnemyType.TURRET_DRONE],
    hazardPalette: [HazardType.GRAVITY_RIFT],
    pickupPalette: [PickupType.OVERCLOCK, PickupType.SHIELD_CELL],
    bossId: 'spindle',
    pickupDropRate: 0.12,
  },
  {
    // Zone 5: Slipstream — lateral flow reversals, mixed enemies
    id: 5,
    name: 'Slipstream',
    scoreToClear: 1260,
    waveCount: 8,
    spawnIntervalMs: { start: 1200, min: 650 },
    maxAsteroids: 30,
    asteroidSizeRange: [18, 44],
    asteroidSpeedRange: [460, 760],
    asteroidDamageRange: [28, 60],
    playfield: { horizontalLimit: 1400, verticalLimit: 700 },
    driftPattern: 'lateral',
    background: { starColor: 0x66ffee, minSpeed: 70, maxSpeed: 260 },
    audioTrackId: 'level5',
    enemyPalette: [EnemyType.RAIDER, EnemyType.BOMBER, EnemyType.SENTINEL],
    hazardPalette: [HazardType.RADIATION_CLOUD, HazardType.DEBRIS_FIELD],
    pickupPalette: [PickupType.SHIELD_CELL, PickupType.HULL_PATCH, PickupType.OVERCLOCK],
    bossId: 'leviathan',
    pickupDropRate: 0.15,
  },
  {
    // Zone 6: Core Storm — maximum intensity
    id: 6,
    name: 'Core Storm',
    scoreToClear: 1890,
    waveCount: 8,
    spawnIntervalMs: { start: 1050, min: 650 },
    maxAsteroids: 30,
    asteroidSizeRange: [16, 52],
    asteroidSpeedRange: [520, 880],
    asteroidDamageRange: [35, 80],
    playfield: { horizontalLimit: 1400, verticalLimit: 700 },
    driftPattern: 'surge',
    background: { starColor: 0x55ccff, minSpeed: 90, maxSpeed: 320 },
    audioTrackId: 'level6',
    enemyPalette: [EnemyType.STRIKER, EnemyType.BOMBER, EnemyType.SENTINEL, EnemyType.CARRIER_POD],
    hazardPalette: [HazardType.GRAVITY_RIFT, HazardType.RADIATION_CLOUD, HazardType.DEBRIS_FIELD],
    pickupPalette: [PickupType.OVERCLOCK, PickupType.HULL_PATCH],
    bossId: 'apex',
    pickupDropRate: 0.10,
  },
];

export const MAX_ZONE_ID = ZONE_CONFIGS[ZONE_CONFIGS.length - 1].id;
